自己紹介C完了 fix #9
omorirenka/gitremote pull request #13
Opened 2023-10-25 06:04 UTC by useruser0123

2023-10-25 06:05 UTC, omorirenka approved these changes
レビューしました

2023-10-25 06:05 UTC, omorirenka commented on hoge.txt
> +my name is CCC
CCCを修正お願いします

2023-10-25 06:06 UTC, itouayumu requested changes
修正お願いします～

2023-10-25 06:06 UTC, itouayumu commented on hoge.txt
> +my name is CCC
Cの方がいいんじゃない？

2023-10-31 05:56 UTC, itouayumu approved these changes
ok

2023-10-31 05:56 UTC, merged